name: cef_texture_browser
description: A Rust FFI and off-screen browser rendering probe for Flutter Linux.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  code_assets: ^1.2.1
  ffi: ^2.2.0
  flutter:
    sdk: flutter
  hooks: ^2.2.0
  irondash_engine_context: ^0.5.5
  marionette_flutter: ^0.6.0
  native_toolchain_rust: ^1.0.6

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
